"""added quantity_value and quantity_unit

Revision ID: 513b11c3c536
Revises: 200b1c10599b
Create Date: 2025-12-07 20:13:42.163635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513b11c3c536'
down_revision: Union[str, Sequence[str], None] = '200b1c10599b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    op.drop_index(op.f('ix_FoodItem_fooditem_id'), table_name='FoodItem')
    op.drop_index(op.f('ix_FoodItem_fooditem_name'), table_name='FoodItem')
    op.drop_table('FoodItem')
    op.drop_table('Kitchen')
    op.drop_index(op.f('ix_project_users_user_id'), table_name='project_users')
    op.drop_index(op.f('ix_project_users_username'), table_name='project_users')
    op.drop_table('project_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_users',
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('project_users_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='project_users_pkey'),
    sa.UniqueConstraint('email', name='project_users_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_project_users_username'), 'project_users', ['username'], unique=True)
    op.create_index(op.f('ix_project_users_user_id'), 'project_users', ['user_id'], unique=False)
    op.create_table('Kitchen',
    sa.Column('kitchen_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('kitchen_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['project_users.user_id'], name=op.f('Kitchen_owner_id_fkey')),
    sa.PrimaryKeyConstraint('kitchen_id', name=op.f('Kitchen_pkey'))
    )
    op.create_table('FoodItem',
    sa.Column('fooditem_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fooditem_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fooditem_image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expirary_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('kitchen_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['kitchen_id'], ['project_users.user_id'], name=op.f('FoodItem_kitchen_id_fkey')),
    sa.PrimaryKeyConstraint('fooditem_id', name=op.f('FoodItem_pkey'))
    )
    op.create_index(op.f('ix_FoodItem_fooditem_name'), 'FoodItem', ['fooditem_name'], unique=False)
    op.create_index(op.f('ix_FoodItem_fooditem_id'), 'FoodItem', ['fooditem_id'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('User_pkey')),
    sa.UniqueConstraint('email', name=op.f('User_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('User_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
