"""sync correct models

Revision ID: c7c8a000e656
Revises: 513b11c3c536
Create Date: 2025-12-07 20:20:09.930059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c8a000e656'
down_revision: Union[str, Sequence[str], None] = '513b11c3c536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_project_users_user_id'), 'project_users', ['user_id'], unique=False)
    op.create_index(op.f('ix_project_users_username'), 'project_users', ['username'], unique=True)
    op.create_table('Kitchen',
    sa.Column('kitchen_id', sa.Integer(), nullable=False),
    sa.Column('kitchen_name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['project_users.user_id'], ),
    sa.PrimaryKeyConstraint('kitchen_id')
    )
    op.create_index(op.f('ix_Kitchen_kitchen_id'), 'Kitchen', ['kitchen_id'], unique=False)
    op.create_table('FoodItem',
    sa.Column('fooditem_id', sa.Integer(), nullable=False),
    sa.Column('fooditem_name', sa.String(), nullable=False),
    sa.Column('fooditem_image', sa.String(), nullable=True),
    sa.Column('expirary_date', sa.Date(), nullable=True),
    sa.Column('quantity_value', sa.Integer(), nullable=True),
    sa.Column('quantity_unit', sa.String(), nullable=True),
    sa.Column('kitchen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kitchen_id'], ['Kitchen.kitchen_id'], ),
    sa.PrimaryKeyConstraint('fooditem_id')
    )
    op.create_index(op.f('ix_FoodItem_fooditem_id'), 'FoodItem', ['fooditem_id'], unique=False)
    op.create_index(op.f('ix_FoodItem_fooditem_name'), 'FoodItem', ['fooditem_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_FoodItem_fooditem_name'), table_name='FoodItem')
    op.drop_index(op.f('ix_FoodItem_fooditem_id'), table_name='FoodItem')
    op.drop_table('FoodItem')
    op.drop_index(op.f('ix_Kitchen_kitchen_id'), table_name='Kitchen')
    op.drop_table('Kitchen')
    op.drop_index(op.f('ix_project_users_username'), table_name='project_users')
    op.drop_index(op.f('ix_project_users_user_id'), table_name='project_users')
    op.drop_table('project_users')
    # ### end Alembic commands ###
